/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Activity = IDL.Variant({
  'reading' : IDL.Null,
  'meditation' : IDL.Null,
  'music' : IDL.Null,
  'exercise' : IDL.Null,
  'sleep' : IDL.Null,
});
export const Mood = IDL.Variant({
  'sad' : IDL.Null,
  'happy' : IDL.Null,
  'angry' : IDL.Null,
  'stressed' : IDL.Null,
  'neutral' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ActivityEntry = IDL.Record({
  'timestamp' : Time,
  'activity' : Activity,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const MoodEntry = IDL.Record({ 'mood' : Mood, 'timestamp' : Time });
export const WellnessReport = IDL.Record({
  'recentActivities' : IDL.Vec(ActivityEntry),
  'recentMoods' : IDL.Vec(MoodEntry),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addActivityEntry' : IDL.Func([Activity], [], []),
  'addMoodEntry' : IDL.Func([Mood], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getActivityHistory' : IDL.Func([], [IDL.Vec(ActivityEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMoodFrequency' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Mood, IDL.Nat))],
      ['query'],
    ),
  'getMoodHistory' : IDL.Func([], [IDL.Vec(MoodEntry)], ['query']),
  'getMoodStreak' : IDL.Func([], [IDL.Nat], ['query']),
  'getMostRecentMood' : IDL.Func([], [IDL.Opt(MoodEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWellnessReport' : IDL.Func([], [WellnessReport], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Activity = IDL.Variant({
    'reading' : IDL.Null,
    'meditation' : IDL.Null,
    'music' : IDL.Null,
    'exercise' : IDL.Null,
    'sleep' : IDL.Null,
  });
  const Mood = IDL.Variant({
    'sad' : IDL.Null,
    'happy' : IDL.Null,
    'angry' : IDL.Null,
    'stressed' : IDL.Null,
    'neutral' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ActivityEntry = IDL.Record({
    'timestamp' : Time,
    'activity' : Activity,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const MoodEntry = IDL.Record({ 'mood' : Mood, 'timestamp' : Time });
  const WellnessReport = IDL.Record({
    'recentActivities' : IDL.Vec(ActivityEntry),
    'recentMoods' : IDL.Vec(MoodEntry),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addActivityEntry' : IDL.Func([Activity], [], []),
    'addMoodEntry' : IDL.Func([Mood], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getActivityHistory' : IDL.Func([], [IDL.Vec(ActivityEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMoodFrequency' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Mood, IDL.Nat))],
        ['query'],
      ),
    'getMoodHistory' : IDL.Func([], [IDL.Vec(MoodEntry)], ['query']),
    'getMoodStreak' : IDL.Func([], [IDL.Nat], ['query']),
    'getMostRecentMood' : IDL.Func([], [IDL.Opt(MoodEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWellnessReport' : IDL.Func([], [WellnessReport], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };