/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Activity = { 'reading' : null } |
  { 'meditation' : null } |
  { 'music' : null } |
  { 'exercise' : null } |
  { 'sleep' : null };
export interface ActivityEntry { 'timestamp' : Time, 'activity' : Activity }
export type Mood = { 'sad' : null } |
  { 'happy' : null } |
  { 'angry' : null } |
  { 'stressed' : null } |
  { 'neutral' : null };
export interface MoodEntry { 'mood' : Mood, 'timestamp' : Time }
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WellnessReport {
  'recentActivities' : Array<ActivityEntry>,
  'recentMoods' : Array<MoodEntry>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addActivityEntry' : ActorMethod<[Activity], undefined>,
  'addMoodEntry' : ActorMethod<[Mood], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getActivityHistory' : ActorMethod<[], Array<ActivityEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMoodFrequency' : ActorMethod<[], Array<[Mood, bigint]>>,
  'getMoodHistory' : ActorMethod<[], Array<MoodEntry>>,
  'getMoodStreak' : ActorMethod<[], bigint>,
  'getMostRecentMood' : ActorMethod<[], [] | [MoodEntry]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWellnessReport' : ActorMethod<[], WellnessReport>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];